userauth/multiuserauth/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='mutliuserauth'

urlpatterns = [
   
    path('', views.login ,name='login'),
    path('logout', views.logoutuser ,name='logoutuser'),
    path('admin-dashboard/', views.admin_dashboard ,name='admin_dashboard'),
    path('agent_register/', views.agent_register ,name='agent_register'),
    path('agent_dashboard/', views.agent_dashboard ,name='agent_dashboard'),
    path('customer_dashboard/', views.customer_dashboard ,name='customer_dashboard'),
]

userauth/userauth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('multiuserauth.urls',namespace='multiuserauth'))
]

userauth/multiuserauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager


class CustomUserManager(BaseUserManager):
    def create_user(self, usename, password, **extra_fields):
        if not usename:
            raise ValueError(_('The usename must be set'))
        user = self.model(username=usename, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('user_type', 'admin')
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(username, password, **extra_fields)




USER_TYPE_COICES = (('agent','Agent'),
                    ('admin','Admin'),
                    ('customers','Customers'))


class User(AbstractUser):
    user_type = models.CharField(choices=USER_TYPE_COICES,max_length=50)
    username = models.CharField(max_length=200,unique=True)
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True,null=True,blank=True)
    is_staff = models.BooleanField(default=True,null=True,blank=True)
    is_active = models.BooleanField(default=True,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    last_login = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['password']

    objects = CustomUserManager()


class Agent(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='user_agent')
    name = models.CharField(max_length=120)
    address = models.TextField()


class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='user_customer')
    name = models.CharField(max_length=120)
    address = models.TextField()

userauth/multiuserauth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login,logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from .models import User,Agent,Customer


def login(request):
    if request.method == 'POST' :
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username,password=password)
        if user is not None:
            auth_login(request, user)
            if user.user_type == 'admin' :
                return redirect('multiuserauth:admin_dashboard')
            elif user.user_type == 'agent' :
                return redirect('multiuserauth:agent_dashboard')
            
            elif user.user_type == 'customers':
                return redirect('multiuserauth:customer_dashboard')
            else:
                 return redirect('multiuserauth:login')
    return render(request,'login.html')



def agent_register(request):
    if request.method == "POST":
        username = request.POST.get("username")
       
        password = request.POST.get("password")
        first_name =  request.POST.get("firstname")
        last_name =  request.POST.get("lastname")
        usertype = request.POST.get("usertype")
        print(usertype)
        address = request.POST.get("address")
        user = User.objects.create(username=username, password=make_password(password), first_name=first_name, last_name=last_name, user_type=usertype)
        if user.user_type == 'agent' :
            Agent.objects.create(user=user, name=username, address=address)
        elif user.user_type == 'customers' :
            Customer.objects.create(user=user, name=username, address=address)
        else :
            return redirect('multiuserauth:admin_dashboard') 

        
        # Create an associated Agent instance
        return redirect('multiuserauth:admin_dashboard') 
    
    return redirect('multiuserauth:admin_dashboard') 



@login_required
def admin_dashboard(request):
    return render(request, 'administrator/adminpage.html')

@login_required
def agent_dashboard(request):
    return render(request, 'agent/agentpage.html')

@login_required
def customer_dashboard(request):
    return render(request, 'customer/customerpage.html')


def logoutuser(request):
    logout(request)
    return redirect('multiuserauth:login') 

userauth/templates/administrator/adminpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>

    <h1 class="text-center my-3">Admin Dashboard</h1>


    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <form action="{% url 'multiuserauth:agent_register' %}" method="POST"  class="shadow-sm p-3 mt-4 row">
                    {% csrf_token %}
                    <div class="mb-3 col-md-6">
                        <input type="text" class="form-control" name="username" placeholder="username" id="">
                    </div>
                    <div class="mb-3 col-md-6">
                        <input type="password" class="form-control" name="password" id="password" placeholder="password">
                    </div>
                    <div class="mb-3 col-md-6">
                        <input type="text" class="form-control" name="firstname" id="firstname" placeholder="firstname">
                    </div>

                    <div class="mb-3 col-md-6">
                        <input type="text" class="form-control" name="lastname" id="lastname" placeholder="lastname">
                    </div>
                    <div class="mb-3 col-md-6">
                        <textarea class="form-control" name="address" id="address" placeholder="address"></textarea>
                    </div>

                    <div class="mb-3 col-md-6">
                        <select name="usertype" class="form-select"  id="usertype">
                            <option value="" >select User</option>
                            <option value="agent">Agent</option>
                            <option value="customers">Customers</option>
                        </select>
                    </div>

                    <div class="mb-3">
                        <button class="btn btn-secondary" type="submit">save data</button>
                    </div>


                </form>
            </div>
        </div>
    </div>

    {% if user.is_authenticated %}
    <a href="{% url 'multiuserauth:logoutuser' %}">Logout</a>
{% endif %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>

userauth/templates/agent/agentpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>

    <h1 class="text-center my-3">agent Dashboard - {{user}}</h1>


    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
               
            </div>
        </div>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'multiuserauth:logoutuser' %}">Logout</a>
{% endif %}


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>

userauth/templates/customer/customerpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>

    <h1 class="text-center my-3">Customer Dashboard - {{user}}</h1>


    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
               
            </div>
        </div>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'multiuserauth:logoutuser' %}">Logout</a>
    {% endif %}


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>

userauth/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>


    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <form action="" class="mt-4" method="POST" >
                    {% csrf_token %}
                    <div class="mb-3">

                        <input type="text" class="form-control" name="username" id="username">
                    </div>

                    <div class="mb-3">

                        <input type="password" class="form-control" name="password" id="password">
                    </div>


                    <button class="btn btn-primary" type="submit">Login</button>
                </form>
            </div>
        </div>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


    <script>
        $(document).ready(function(){

        })
    </script>
</body>
</html>